name: clang-format-check

on:
  pull_request:
    branches:
    - sycl
    paths:
    - '.github/workflows/sycl_cts.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Prepare Env 
      run: sudo apt-get install -y ninja-build cmake build-essential
 
    - uses: actions/checkout@v2
      with:
        # persist-credentials: false allows us to use our own credentials for
        # pushing to the repository.  Otherwise, the default github actions token
        # is used.
        persist-credentials: false
        fetch-depth: 1
        repository: otcshare/llvm_ci
        token: ${{ secrets.DOYLELI_DEBUG_TOKEN }}
        path: llvm_ci
        ref: master

    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: llvm.src

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7.8'

    - name: Run compile 
      run: |
        mkdir llvm.obj

    - name: Run dependency
      run: |
        python3 -u llvm.src/buildbot/dependency.py -n 702 -b sycl -d sycl -w $PWD -s $PWD/llvm.src -o $PWD/llvm.obj -c


