name: clang-format-check

on:
  pull_request:
    branches:
    - sycl
    paths:
    - '.github/workflows/sycl_cts.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Prepare Env 
      run: sudo apt-get install -y ninja-build cmake
 
    - uses: actions/checkout@v2
      with:
        # persist-credentials: false allows us to use our own credentials for
        # pushing to the repository.  Otherwise, the default github actions token
        # is used.
        persist-credentials: false
        fetch-depth: 1
        repository: otcshare/llvm_ci
        path: llvm_ci

    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: llvm.src

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7.8'

    - name: Run dependency
      run: |
        python3 llvm_ci/intel/worker/tools/build.py -b sycl -p sycl -s dependency -c


