name: clang-format-check

on:
  pull_request:
    branches:
    - sycl
    paths:
    - '.github/workflows/sycl_cts.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Prepare Env 
      run: sudo apt-get install -y ninja-build cmake
 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: otcshare/llvm_ci@master
      with:
        fetch-depth: 1

        
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7.8'

    - name: Run dependency
      run: |
        python3 llvm_ci/intel/worker/tools/build.py -b sycl -p sycl -s dependency -c


